package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/kazki/specs-cli/internal/templates"
)

// initScaffold describes a static file generated by `specs init`.
type initScaffold struct {
	path     string // specs/ からの相対パス
	template string // embed されたテンプレート名
}

var initFiles = []initScaffold{
	{path: "product/vision.md", template: "vision.md"},
	{path: "product/principles.md", template: "principles.md"},
	{path: "domain/glossary.md", template: "glossary.md"},
	{path: "domain/models.md", template: "models.md"},
}

// runInit creates the specs/ directory tree with template files.
func runInit(args []string) error {
	if len(args) > 0 {
		return fmt.Errorf("init は引数を取りません")
	}

	root := "specs"
	if _, err := os.Stat(root); err == nil {
		return fmt.Errorf("%s/ は既に存在します", root)
	}

	for _, f := range initFiles {
		dst := filepath.Join(root, f.path)
		content, err := templates.Static(f.template)
		if err != nil {
			return err
		}
		if err := writeFile(dst, content); err != nil {
			return err
		}
		fmt.Printf("created %s\n", dst)
	}

	// features/ は空ディレクトリとして用意する。
	featuresDir := filepath.Join(root, "features")
	if err := os.MkdirAll(featuresDir, 0o755); err != nil {
		return err
	}
	fmt.Printf("created %s/\n", featuresDir)

	return nil
}
