package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/kazki/specs-cli/internal/templates"
)

// initScaffold describes a static file generated by `specs init`.
type initScaffold struct {
	path     string // specs/ からの相対パス
	template string // embed されたテンプレート名
}

var initFiles = []initScaffold{
	{path: "product/vision.md", template: "vision.md"},
	{path: "product/principles.md", template: "principles.md"},
}

// ユビキタス言語 (term) とモデル (model) は 1 件 1 ファイルで管理するため、
// init では空ディレクトリのみ用意する (実体は new term / new model で生成)。
var initDirs = []string{
	"features",
	"domain/glossary",
	"domain/models",
}

// runInit creates the specs/ directory tree with template files.
func runInit(args []string) error {
	if len(args) > 0 {
		return fmt.Errorf("init は引数を取りません")
	}

	root := "specs"
	if _, err := os.Stat(root); err == nil {
		return fmt.Errorf("%s/ は既に存在します", root)
	}

	for _, f := range initFiles {
		dst := filepath.Join(root, f.path)
		content, err := templates.Static(f.template)
		if err != nil {
			return err
		}
		if err := writeFile(dst, content); err != nil {
			return err
		}
		fmt.Printf("created %s\n", dst)
	}

	for _, d := range initDirs {
		dst := filepath.Join(root, d)
		if err := os.MkdirAll(dst, 0o755); err != nil {
			return err
		}
		fmt.Printf("created %s/\n", dst)
	}

	return nil
}
