openapi: 3.1.0
info:
  title: Product API
  version: 0.1.0
  description: |
    Product の API 仕様。
servers:
  - url: /api
paths:
  /product:
    get:
      summary: 一覧取得
      operationId: list_product
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/product"
components:
  schemas:
    product:
      type: object
      properties:
        id:
          type: string
      required:
        - id
